language: python
matrix:
  include:
    - python: 3.5
      env: API_LEVEL=TF1
    - python: 3.7
      sudo: yes
      dist: xenial
      env: API_LEVEL=TF1
# command to install dependencies
install:
  - if [[ "$API_LEVEL" == "TF2" ]]; then
    pip install tf-nightly-2.0-preview;
    else
    pip install tensorflow;
    fi
  - pip install -e .[test]
# command to run tests
script:
  - py.test tests/
notifications:
  email:
    on_success: never
    on_failure: always
